import { Saira } from "next/font/google";
import "./globals.css";
import MainLayout from "@/components/layouts";

const inter = Saira({ subsets: ["latin"] });

export const metadata = {
  title: "Job",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MainLayout />
        <div>{children}</div>
      </body>
    </html>
  );
}
